"""Added programming_languages field in both scraped and cleaned tables

Revision ID: 134b0008e814
Revises: 976b01260198
Create Date: 2025-03-28 14:46:27.175618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134b0008e814'
down_revision: Union[str, None] = '976b01260198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM scraped_data;")
    op.execute("DELETE FROM cleaned_data;")
    op.add_column('cleaned_data', sa.Column('programming_languages', sa.String(), nullable=False))
    op.add_column('scraped_data', sa.Column('programming_languages', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_data', 'programming_languages')
    op.drop_column('cleaned_data', 'programming_languages')
    # ### end Alembic commands ###
