"""Created cleaned data table

Revision ID: 976b01260198
Revises: d3710970e88c
Create Date: 2025-03-27 10:12:08.160864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976b01260198'
down_revision: Union[str, None] = 'd3710970e88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaned_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('responsibilities', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=False),
    sa.Column('extras', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.alter_column('scraped_data', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scraped_data', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('cleaned_data')
    # ### end Alembic commands ###
