"""Created scraped_data table

Revision ID: d3710970e88c
Revises: 
Create Date: 2025-03-26 20:58:50.130847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3710970e88c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_data',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('responsibilities', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=False),
    sa.Column('extras', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_data_id'), table_name='scraped_data')
    op.drop_table('scraped_data')
    # ### end Alembic commands ###
