"""Added industry field to scraped and cleaned tables

Revision ID: f77d52eed3a5
Revises: 134b0008e814
Create Date: 2025-03-31 22:46:47.693249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77d52eed3a5'
down_revision: Union[str, None] = '134b0008e814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cleaned_data', sa.Column('industry', sa.String(), nullable=False))
    op.add_column('scraped_data', sa.Column('industry', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_data', 'industry')
    op.drop_column('cleaned_data', 'industry')
    # ### end Alembic commands ###
